on:
  push:
    branches:
      - main

name: "ShellCheck"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
